// Mocks generated by Mockito 5.4.0 from annotations
// in rick_morty_test/test/character_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mobx/mobx.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_morty_test/models/characters/character.dart' as _i7;
import 'package:rick_morty_test/providers/app_response.dart' as _i3;
import 'package:rick_morty_test/repositores/character_service.dart' as _i4;
import 'package:rick_morty_test/routes/app_routes.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppRoutes_0 extends _i1.SmartFake implements _i2.AppRoutes {
  _FakeAppRoutes_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppResponse_1<T, E> extends _i1.SmartFake
    implements _i3.AppResponse<T, E> {
  _FakeAppResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CharacterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterService extends _i1.Mock implements _i4.CharacterService {
  @override
  _i2.AppRoutes get appRoutes => (super.noSuchMethod(
        Invocation.getter(#appRoutes),
        returnValue: _FakeAppRoutes_0(
          this,
          Invocation.getter(#appRoutes),
        ),
        returnValueForMissingStub: _FakeAppRoutes_0(
          this,
          Invocation.getter(#appRoutes),
        ),
      ) as _i2.AppRoutes);
  @override
  _i5.Future<
      _i3.AppResponse<_i6.ObservableList<_i7.Character>?,
          Exception>> getCharacters([
    int? page,
    String? name,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [
            page,
            name,
          ],
        ),
        returnValue: _i5.Future<
                _i3.AppResponse<_i6.ObservableList<_i7.Character>?,
                    Exception>>.value(
            _FakeAppResponse_1<_i6.ObservableList<_i7.Character>?, Exception>(
          this,
          Invocation.method(
            #getCharacters,
            [
              page,
              name,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i3.AppResponse<_i6.ObservableList<_i7.Character>?,
                    Exception>>.value(
            _FakeAppResponse_1<_i6.ObservableList<_i7.Character>?, Exception>(
          this,
          Invocation.method(
            #getCharacters,
            [
              page,
              name,
            ],
          ),
        )),
      ) as _i5.Future<
          _i3.AppResponse<_i6.ObservableList<_i7.Character>?, Exception>>);
  @override
  _i5.Future<void> setValueShowMessageNotification([String? jsonContent]) =>
      (super.noSuchMethod(
        Invocation.method(
          #setValueShowMessageNotification,
          [jsonContent],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> removeDataNotification() => (super.noSuchMethod(
        Invocation.method(
          #removeDataNotification,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
